### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by linluz** [chenhahacjl/ConfuserEx-Plus#1]
1 漏了一句文本没翻译：local to field Protection (或者说这个保护项 里面的三个字串都没翻译)。
2 堆栈跟踪器 选密码 之后 界面也有一个英文字串未翻译
3 保护项 里面的 Add和remove 可以翻译成 添加和移除吗
4 另外 建议在 工程 标签页中无输入（基础目录和输出目录 其一为空）的时候，把 保护 标签页里的 保护按钮禁用了（当然这可能需要一个计时器作为检测？这个方法会更友好于用户，比如我这种喜欢乱点的）
另外一个更简便的办法就是 在这个按钮的点击方法里加个判定。
否则会出现以下报错

[ERROR] Unknown error occurred.
Exception: System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) 位置 E:\CodeTool\ConfuserEx - MDF\ConfuserEx-Modify\Confuser.Core\ConfuserEngine.cs:行号 98
Failed at 5:57, 0:00 elapsed.

来自一个经常搞无源码汉化的朋友

**Comment by chenhahacjl** [comment]
Fixed At Version d2b6c8ae6fb45637931538a3495dd52148c0c672
